#!/usr/bin/env python3
"""Auto-generate the NOTICES file from installed package metadata.

Requires pip-licenses to be installed (dev dependency).

Usage:
    uv run python scripts/generate_notices.py
"""

from __future__ import annotations

import json
import subprocess
import sys
import textwrap
from pathlib import Path

# Runtime dependencies to include (not dev-only).
RUNTIME_PACKAGES = [
    "faststream",
    "playwright",
    "pyarrow",
    "pydantic",
    "pydantic-settings",
    "aiohttp",
    "obstore",
    "tranco",
    "rich",
    "duckdb",
    "adblock",
    "python-dotenv",
    "tqdm",
    "url-normalize",
    "defopt",
    "nats-py",
    "requests",
]

# Datasets and other non-pip attributions that must be included manually.
MANUAL_ENTRIES = textwrap.dedent("""\
    ========================================================================
    DATASETS
    ========================================================================

    countries (mledoze/countries)
    -----------------------------
    License: Open Data Commons Open Database License (ODbL) v1.0
    Source: https://github.com/mledoze/countries
    Maintained by: mledoze (https://github.com/mledoze)

    This project uses data from the "countries" dataset, which is made
    available under the Open Database License:
    http://opendatacommons.org/licenses/odbl/1.0/

    Any rights in individual contents of the database are licensed under the
    Database Contents License:
    http://opendatacommons.org/licenses/dbcl/1.0/
""")

ROOT = Path(__file__).resolve().parent.parent
NOTICES_PATH = ROOT / "NOTICES"


def get_licenses() -> list[dict]:
    """Call pip-licenses and return structured package info."""
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "piplicenses",
            "--packages",
            *RUNTIME_PACKAGES,
            "--from",
            "all",
            "--format",
            "json",
            "--with-authors",
            "--with-urls",
            "--with-license-file",
            "--no-license-path",
            "--with-notice-file",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def resolve_license(pkg: dict) -> str:
    """Pick the best available license string for a package."""
    for key in ("License-Metadata", "License-Expression", "License-Classifier"):
        val = pkg.get(key, "UNKNOWN")
        if val and val != "UNKNOWN":
            return val
    return "UNKNOWN"


def format_package(pkg: dict) -> str:
    """Format a single package entry for the NOTICES file."""
    name = pkg["Name"]
    version = pkg["Version"]
    author = pkg.get("Author", "UNKNOWN")
    url = pkg.get("URL", "UNKNOWN")
    license_id = resolve_license(pkg)
    license_text = pkg.get("LicenseText", "UNKNOWN")
    notice_text = pkg.get("NoticeText", "UNKNOWN")

    lines = [
        f"{name} {version}",
        "-" * len(f"{name} {version}"),
    ]
    if author and author != "UNKNOWN":
        lines.append(f"Author: {author}")
    lines.append(f"License: {license_id}")
    if url and url != "UNKNOWN":
        lines.append(f"Source: {url}")
    lines.append("")

    if license_text and license_text != "UNKNOWN":
        lines.append(license_text.rstrip())
        lines.append("")

    if notice_text and notice_text != "UNKNOWN":
        lines.append("NOTICE:")
        lines.append(notice_text.rstrip())
        lines.append("")

    return "\n".join(lines)


def main():
    packages = get_licenses()
    packages.sort(key=lambda p: p["Name"].lower())

    sections: list[str] = []
    sections.append(
        "distcrawl - Third-Party Notices\n"
        "================================\n"
        "\n"
        "This file is auto-generated by scripts/generate_notices.py.\n"
        "Do not edit manually. Re-run the script after updating dependencies.\n"
    )

    sections.append(MANUAL_ENTRIES)

    sections.append(
        "========================================================================\n"
        "SOFTWARE DEPENDENCIES\n"
        "========================================================================"
    )

    for pkg in packages:
        sections.append(format_package(pkg))
        sections.append(
            "------------------------------------------------------------------------"
        )

    text = "\n\n".join(sections) + "\n"
    NOTICES_PATH.write_text(text)
    print(f"Wrote {NOTICES_PATH} ({len(packages)} packages)")


if __name__ == "__main__":
    main()
